CREATE TABLE IF NOT EXISTS invite_tokens (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  org_id VARCHAR(64) NOT NULL,
  token VARCHAR(128) NOT NULL,
  token_type VARCHAR(20) NOT NULL DEFAULT 'normal',
  active TINYINT(1) NOT NULL DEFAULT 1,
  used TINYINT(1) NOT NULL DEFAULT 0,
  expires_at DATETIME NULL,
  used_at DATETIME NULL,
  used_by VARCHAR(255) NULL,
  created_by VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_org_token (org_id, token),
  KEY idx_org_active_used (org_id, active, used),
  KEY idx_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS member_counters (
  org_id VARCHAR(64) NOT NULL,
  next_value INT UNSIGNED NOT NULL DEFAULT 1,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (org_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  org_id VARCHAR(64) NOT NULL,
  member_number VARCHAR(32) NOT NULL,
  invite_token VARCHAR(128) NULL,
  anrede VARCHAR(32) NULL,
  titel VARCHAR(64) NULL,
  vorname VARCHAR(120) NOT NULL,
  nachname VARCHAR(120) NOT NULL,
  geburtsdatum VARCHAR(20) NOT NULL,
  beruf VARCHAR(150) NULL,
  geburtsort VARCHAR(150) NULL,
  familienstand VARCHAR(100) NULL,
  staatsburgerschaft VARCHAR(100) NULL,
  identifikationsnummer VARCHAR(120) NOT NULL,
  telefonnummer VARCHAR(80) NULL,
  forumsname VARCHAR(120) NULL,
  discord_id VARCHAR(40) NULL,
  adresse VARCHAR(255) NULL,
  postleitzahl VARCHAR(16) NULL,
  stadt VARCHAR(120) NULL,
  dmail VARCHAR(255) NOT NULL,
  personalbild_url VARCHAR(500) NULL,
  login_mail VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  mitglied_seit VARCHAR(20) NULL,
  aktueller_dienstgrad VARCHAR(80) NULL,
  letzte_beforderung VARCHAR(20) NULL,
  funktion VARCHAR(120) NULL,
  ausbildner VARCHAR(20) NULL,
  ausbildner_fur VARCHAR(120) NULL,
  dienstzuteilung VARCHAR(200) NULL,
  aktives_mitglied VARCHAR(20) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_org_member_number (org_id, member_number),
  UNIQUE KEY uq_org_login_mail (org_id, login_mail)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
